sealed class Instruction {
    data class Store(val register: Int, val value: Int) : Instruction()
    data class Add(val rX: Int, val rY: Int, val rZ: Int) : Instruction()
    data class Sub(val rX: Int, val rY: Int, val rZ: Int) : Instruction()
    data class Read(val rX: Int) : Instruction()
    data class Write(val rX: Int) : Instruction()
    data class Jump(val address: Int) : Instruction()
    data class ReadKeyboard(val rX: Int) : Instruction()
    object SwitchMemory : Instruction()
    data class SkipEqual(val rX: Int, val rY: Int) : Instruction()
    data class SkipNotEqual(val rX: Int, val rY: Int) : Instruction()
    data class SetA(val value: Int) : Instruction()
    data class SetT(val value: Int) : Instruction()
    data class ReadT(val rX: Int) : Instruction()
    data class ConvertToBase10(val rX: Int) : Instruction()
    data class ConvertByteToASCII(val rX: Int, val rY: Int) : Instruction()
    data class Draw(val rX: Int, val rY: Int, val rZ: Int) : Instruction()
}
